name: ift6759-env
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - numpy
  - pandas
  - pip
  - matplotlib
  - seaborn
  - plotly
  - jupyterlab>=3.0.0
  - tqdm
  - pip:
    - torch
    - torchvision
    - pyyaml
