---
# "super" - supervised learning, "semi" - semi supervised learning, "shot" - few shot learning
task: "semi"

data: "cifar10"
model: "resnet"
augment: 

aug_strength:

eval:
    "Acc"
       
batch_size: 250
learning_rate: 0.001
momentum: 0.9
epoch: 50
optimizer: "sgd"
weight_decay: 0.1
seed: 6759

