---
# "super" - supervised learning, "semi" - semi supervised learning, "shot" - few shot learning
task: "super"

data: "cifar10"
model: "resnet"
augment: 
    - "Flip"
    - "Translation"
    - "Rotation"
    - "ContrastBrightness"
    - "GaussBlur"

aug_strength:
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    - 0.2

eval:
    "Acc"
       
batch_size: 250
learning_rate: 0.01
epoch: 100
optimizer: "adam"
weight_decay: 0
seed: 6759

