---
# "super" - supervised learning, "semi" - semi supervised learning, "shot" - few shot learning
num: 03
task: "semi"

data: "cifar10"
model: "all_cnn"
augment: 
    - "Rotation"

aug_strength:
    - 1

eval:
    "Acc"
       
batch_size: 256
learning_rate: 0.01
epoch: 175
optimizer: "sgd"
weight_decay: 0.001
momentum : 0.9
seed: 6769

